### ISSUE TITLE
EdgeX controller and EdgeX components work in different namespace

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/yurt-edgex-manager#1]
From the demo video, I have seen that EdgeX controller is deployed in the edgex-system namespace, but EdgeX components are deployed in default namespace. Would you agree with  that deploy EdgeX components in edgex-system namespace is more reasonable?

**Comment by rambohe-ch** [comment]
@lwmqwer

**Comment by lwmqwer** [comment]
The edgeX is namespace Custom resource, in this example I do not set the namespace of EdgeX so it is defualt, but used can set the EdgeX CR in some namespace and its related service and unitedeployment in the same name space. This is same as the kube-controller-manager in the kube-system namespace but pod can in any namespace.
