### ISSUE TITLE
[feature request] Write the v1alpha2 webhook and enable it

### ISSUE THREAD

**Issue by LavenderQAQ** [openyurtio/yurt-edgex-manager#101]
**What would you like to be added**:
Currently our edgex crd already supports v1alpha2 version, we need to enable v1alpha2 webhook.
- Continue most of the functionality of the v1alpha1 webhook
- v1alpha1 webhooks check edgex versions, but only hanoi and jakarta are supported, after we upgrade the version, the version currently supported by edgex will be stored in `config.json`. webhook needs to read all supported versions and determine if the version deployed by the user is supported by us.
- Enable the new version of webhook in the main function and close the old version of webhook.

**Why is this needed**:
Ensure that the v1alpha2 information passed to controller is correct.

**others**
/kind feature

**Comment by Pluviophile225** [comment]
I am interested in this issue. Can you assign it to me?

**Comment by wangxye** [comment]
I am interested in this issue. Can I do this task?
