### ISSUE TITLE
[feature request] edgex service support override configuration via EdgeX CR additinaldeployments field

### ISSUE THREAD

**Issue by watjt** [openyurtio/yurt-edgex-manager#14]
Problem:
I want modify edgex service configurations, like core-data/core-metadata etc, we must rebuild yurt-edgex-manager image or manual modify deployment configurations after create EdgeX CR.

Idea: 
If EdgeX CR additinaldeployments and additinalservices fields can override default edgex services configuration (yurt-edgex-manager/EdgeXConfig) , this problem can be solved.

**Comment by lwmqwer** [comment]
> Problem: I want modify edgex service configurations, like core-data/core-metadata etc, we must rebuild yurt-edgex-manager image or manual modify deployment configurations after create EdgeX CR.
> 
> Idea: If EdgeX CR additinaldeployments and additinalservices fields can override default edgex services configuration (yurt-edgex-manager/EdgeXConfig) , this problem can be solved.

This looks great that we allow user to modify the core deployment and service.  But we must choose a unique key to identify the deployment and service. I would use the name now. If the additional services or deployments have the same name as the core. these would replace the core one.
