### ISSUE TITLE
updating to the newest edgex foundry version jakarta

### ISSUE THREAD

**Issue by charithmadhuranga** [openyurtio/yurt-edgex-manager#3]
issue- current version is including the  hanoi release which is using the old  v1 api.Current release of edgex is build on the new api v2.
expect - update the example to the current edgex release

**Comment by rambohe-ch** [comment]
@charithmadhuranga Thank you for raising issue. we are discussing the features that will be supported in the next version, and support EdgeX 2.0+ is included.

**Comment by rambohe-ch** [comment]
@lwmqwer Do you have any comments?

**Comment by lwmqwer** [comment]
@charithmadhuranga Support new version edgex is one of the plan in next version and we also welcome any one PR for it

**Comment by huiwq1990** [comment]
> @charithmadhuranga Support new version edgex is one of the plan in next version and we also welcome any one PR for it

When will the new version release? I also ask in  https://github.com/openyurtio/yurt-device-controller/issues/25. By the way, how can I contribute this feature.

**Comment by lwmqwer** [comment]
> > @charithmadhuranga Support new version edgex is one of the plan in next version and we also welcome any one PR for it
> 
> When will the new version release? I also ask in [openyurtio/yurt-device-controller#25](https://github.com/openyurtio/yurt-device-controller/issues/25). By the way, how can I contribute this feature.

The official release will be in OpenYurt v0.7/0.8. But I am working on it recent week. 
The yurt-edgex-manager function is almost over. After test, I will merge it.
About the contribution, You can raise any PR that if you think the yurt-edgex-manager do not cover. Besides, the web-hooks, documents and CI/CD are also welcome.

**Comment by huiwq1990** [comment]
To be honest, I want use `openyurt` to support my bussiness. I was pressed for time to give the plan. So after the new version merged, we can work together.
