### ISSUE TITLE
support helm install

### ISSUE THREAD

**Issue by huiwq1990** [openyurtio/yurt-edgex-manager#5]
How about add a subchart in project [yurtcluster-operator](https://github.com/openyurtio/yurtcluster-operator/tree/main/charts), so we can install `yurt-edgex-manager` easily.

**Comment by lwmqwer** [comment]
> 



> How about add a subchart in project [yurtcluster-operator](https://github.com/openyurtio/yurtcluster-operator/tree/main/charts), so we can install `yurt-edgex-manager` easily.

@rambohe-ch This is good advice, we my consider how to install openyurt componet in a single cmd.

**Comment by huiwq1990** [comment]
> > 
> 
> > How about add a subchart in project [yurtcluster-operator](https://github.com/openyurtio/yurtcluster-operator/tree/main/charts), so we can install `yurt-edgex-manager` easily.
> 
> @rambohe-ch This is good advice, we my consider how to install openyurt componet in a single cmd.

Have you work on it? Which plane would you prefer?

**Comment by lwmqwer** [comment]
Close this issue, all component helm will put int openyurt-helm  repo
