### ISSUE TITLE
[EdgeX Auto-Collector] Synchronize the images of edgex to openyurt

### ISSUE THREAD

**Issue by LavenderQAQ** [openyurtio/yurt-edgex-manager#60]
**What would you like to be added**:
When we collect the edgex configuration, we need to pull the image according to the image field of each component and push it to the repo of openyurt.
All of the images have been collected in the Image field of `Component`. You may want to add a image synchronization feature to `Version` or `Component` and call it when appropriate.

**Why is this needed**:
Refer to [EdgeX Auto-colllector Proposal](https://github.com/openyurtio/openyurt/blob/master/docs/proposals/20221109-edgex-auto-collector.md#images-management)

**others**
/kind feature

**Comment by yangbobo6** [comment]
I am very interested in this issue, I'll solve that
