### ISSUE TITLE
[EdgeX Auto-Collector] Rewrite the controller part which read the edgex configuration section

### ISSUE THREAD

**Issue by LavenderQAQ** [openyurtio/yurt-edgex-manager#62]
**What would you like to be added**:
We need to change the controller to read new config yaml. The controller reads each version and creates the component that the user needs.
This issue will have to wait #61 

**Why is this needed**:
Refer to [EdgeX Auto-colllector Proposal](https://github.com/openyurtio/openyurt/blob/master/docs/proposals/20221109-edgex-auto-collector.md#images-management)

**others**
/kind feature

**Comment by Rui-Gan** [comment]
I will solve this issue after #61 and #66 are finished
