### ISSUE TITLE
[EdgeX Auto-Collector] Upgrade apiVersion and deprecate additionalServices and additionalDeployments in new version

### ISSUE THREAD

**Issue by LavenderQAQ** [openyurtio/yurt-edgex-manager#68]
**What would you like to be added**:
We will modify the spec of yurt-edgex-manager at this stage. The previous additionalServices and additionalDeployments fields are not user-friendly. We need to change them to the components field and in the next step give the user an easier way to configure them.
We need to upgrade api version to `v1alpha2`

**Why is this needed**:
Refer to [EdgeX Auto-colllector Proposal](https://github.com/openyurtio/openyurt/blob/master/docs/proposals/20221109-edgex-auto-collector.md#images-management)

**others**
/kind feature

**Comment by Rui-Gan** [comment]
Completed, see #86  for details
