### ISSUE TITLE
[feature request] refactor yurt-edgex-manager to yurt-iot-manager

### ISSUE THREAD

**Issue by wawlian** [openyurtio/yurt-edgex-manager#92]
**What would you like to be added**:
1. rename yurt-edgex-manager to yurt-iot-manager
2. yurt-iot-manager will responsible for the deployment of yurt-device-controller

**Why is this needed**:
1. yurt-iot-manager will responsible for the lifecycle of all the components within the IoT sig
2. support more platforms like EdgeX Foundry in the near future

**others**
/kind feature

**Comment by LavenderQAQ** [comment]
At present, @Rui-Gan  have renamed Edgex-Manager to iot-manager in pr merged to main warehouse, and added platform field (the default is edgex, the user's usage remains the same).
refer: https://github.com/openyurtio/openyurt/pull/1488

**Comment by Rui-Gan** [comment]
I am interested in this issue. Can I do this task?
