### ISSUE TITLE
[Feature Request]provide minimal set of components by default to reduce resource consumption

### ISSUE THREAD

**Issue by wawlian** [openyurtio/yurt-edgex-manager#97]
EdgeX Foundry has include several micro-services, some of which are not necessary by default. Since thelevski version, the inter-communication method changed from REST to message bus which lead to some more unnecessary components.

We hope that Iot-Manager could deploy a minimal set of necessary  components by default to reduce resources consumption. Meanwhile, could allow users to customize add more optional components.

**Comment by LavenderQAQ** [comment]
This issue has been solved by [this pr](https://github.com/openyurtio/openyurt/pull/1650).
